### model
model_name_or_path: "/mnt/nvme/home/zr/models/Qwen3-32B/"
trust_remote_code: true

### method
stage: "sft"
do_train: true
template: "qwen3"
finetuning_type: "lora"
lora_rank: 8
lora_alpha: 16
lora_dropout: 0.05
lora_target: ["q_proj", "k_proj", "v_proj", "o_proj"]
flash_attn: fa2

### dataset
dataset: training_pathology
cutoff_len: 16384
overwrite_cache: true
preprocessing_num_workers: 8

### output
output_dir: "outputs/clinico_pathology_sft_lora_0126"
logging_steps: 100
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: "none"

### train
per_device_train_batch_size: 4 
gradient_accumulation_steps: 8
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: "cosine"
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null
